export 'package:widgetsapp/presentation/screens/animated/animated_screen.dart';
export 'package:widgetsapp/presentation/screens/app_tutorial/app_tutorial_screen.dart';
export 'package:widgetsapp/presentation/screens/infinite_scroll/infinite_scroll_screen.dart';
export 'package:widgetsapp/presentation/screens/progress/progress_screen.dart';
export 'package:widgetsapp/presentation/screens/snackbar/snackbar_screen.dart';
export 'package:widgetsapp/presentation/screens/ui_constrols/ui_controls_screnn.dart';
export 'package:widgetsapp/presentation/screens/cards/cards_screen.dart';
export 'package:widgetsapp/presentation/screens/home/home_screen.dart';
export 'package:widgetsapp/presentation/screens/buttons/buttons_screen.dart';
